### PR TITLE
ImprovedVectorCopy

### PR DESCRIPTION
**Pull request by Anderman**
small changes.
use reg vars for pSrc  and pDst
faster copy of 0-15 bytes

### CODE REVIEW

**Comment by nietras** [comment]
@Anderman thanks!

**Comment by nietras** [comment]
@Anderman I do have a question, though. As far as I can see your code is based on the implicit assumption that `Vector<byte>.Count` is 16 otherwise the code won't work since the `switch/case` only handles <=15. This means this won't work with AVX/AVX2 does it not?

**Comment by nietras** [comment]
@Anderman I added a test step to test which found a bug in the illyriad version. I ran the benchmarks on my i5-3475S where the `nietras` version is actually just your version but using a `Buffer16` struct instead. I've renamed it in the latest commit. As can be seen before 64 bytes your version is fastest, excl 0-15.

image

**Comment by Anderman** [comment]
Thanks

**Pull request merged**
